CREATE DATABASE IF NOT EXISTS "biblioteca";
USE biblioteca;

CREATE TABLE IF NOT EXISTS libros(
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   titulo VARCHAR(100) NOT NULL,
   autor VARCHAR(100) NOT NULL
 );

